import { Subscription, User, Payment } from '@/shared/types';

export const mockUser: User = {
  id: 'user123',
  walletAddress: 'addr1qxy2lpan99fcnyjz4c2n72w57h2xvz8hw58j8hxrz6j4w2c5jnh8u3m8z4j2w9f5t6r7s8u9v0x1y2z3',
  createdAt: '2025-01-15T10:30:00Z',
  preferences: {
    currency: 'ADA',
    theme: 'light',
  },
  budgetLimit: 100,
};

export const mockSubscriptions: Subscription[] = [
  {
    id: '1',
    userId: 'user123',
    planId: 'plan1',
    planName: 'Premium',
    merchantName: 'Cardano News',
    amount: 10,
    currency: 'ADA',
    interval: 'monthly',
    status: 'active',
    nextPaymentDate: '2025-12-01',
    vaultAddress: 'addr1qx...',
    createdAt: '2025-11-01T10:00:00Z',
  },
  {
    id: '2',
    userId: 'user123',
    planId: 'plan2',
    planName: 'Pro',
    merchantName: 'DeFi Analytics',
    amount: 15,
    currency: 'ADA',
    interval: 'monthly',
    status: 'active',
    nextPaymentDate: '2025-12-05',
    vaultAddress: 'addr1qx...',
    createdAt: '2025-10-15T14:30:00Z',
  },
  {
    id: '3',
    userId: 'user123',
    planId: 'plan3',
    planName: 'Basic',
    merchantName: 'Cardano DAO',
    amount: 5,
    currency: 'ADA',
    interval: 'monthly',
    status: 'active',
    nextPaymentDate: '2025-12-10',
    vaultAddress: 'addr1qx...',
    createdAt: '2025-09-20T09:15:00Z',
  },
  {
    id: '4',
    userId: 'user123',
    planId: 'plan4',
    planName: 'Enterprise',
    merchantName: 'NFT Marketplace',
    amount: 25,
    currency: 'ADA',
    interval: 'monthly',
    status: 'active',
    nextPaymentDate: '2025-12-15',
    vaultAddress: 'addr1qx...',
    createdAt: '2025-08-10T16:45:00Z',
  },
  {
    id: '5',
    userId: 'user123',
    planId: 'plan5',
    planName: 'Premium Plus',
    merchantName: 'Wallet Services',
    amount: 20,
    currency: 'ADA',
    interval: 'monthly',
    status: 'paused',
    nextPaymentDate: '2025-12-20',
    vaultAddress: 'addr1qx...',
    createdAt: '2025-07-05T11:20:00Z',
  },
  {
    id: '6',
    userId: 'user123',
    planId: 'plan6',
    planName: 'Starter',
    merchantName: 'Staking Pool',
    amount: 8,
    currency: 'ADA',
    interval: 'monthly',
    status: 'active',
    nextPaymentDate: '2025-12-22',
    vaultAddress: 'addr1qx...',
    createdAt: '2025-06-15T13:00:00Z',
  },
  {
    id: '7',
    userId: 'user123',
    planId: 'plan7',
    planName: 'Annual',
    merchantName: 'Dev Tools',
    amount: 100,
    currency: 'ADA',
    interval: 'yearly',
    status: 'active',
    nextPaymentDate: '2026-01-15',
    vaultAddress: 'addr1qx...',
    createdAt: '2025-01-15T08:30:00Z',
  },
  {
    id: '8',
    userId: 'user123',
    planId: 'plan8',
    planName: 'Pro',
    merchantName: 'Content Platform',
    amount: 12,
    currency: 'ADA',
    interval: 'monthly',
    status: 'active',
    nextPaymentDate: '2025-12-28',
    vaultAddress: 'addr1qx...',
    createdAt: '2025-05-20T15:45:00Z',
  },
  {
    id: '9',
    userId: 'user123',
    planId: 'plan9',
    planName: 'Basic',
    merchantName: 'Security Tools',
    amount: 7,
    currency: 'ADA',
    interval: 'monthly',
    status: 'cancelled',
    nextPaymentDate: '2025-11-30',
    vaultAddress: 'addr1qx...',
    createdAt: '2025-04-10T12:00:00Z',
  },
  {
    id: '10',
    userId: 'user123',
    planId: 'plan10',
    planName: 'Premium',
    merchantName: 'Analytics Dashboard',
    amount: 18,
    currency: 'ADA',
    interval: 'monthly',
    status: 'active',
    nextPaymentDate: '2025-12-30',
    vaultAddress: 'addr1qx...',
    createdAt: '2025-03-05T10:15:00Z',
  },
];

export const mockPayments: Payment[] = [
  {
    id: 'pay1',
    subscriptionId: '1',
    amount: 10,
    currency: 'ADA',
    status: 'success',
    txHash: 'abc123def456',
    executedAt: '2025-11-01T10:00:00Z',
  },
  {
    id: 'pay2',
    subscriptionId: '2',
    amount: 15,
    currency: 'ADA',
    status: 'success',
    txHash: 'def456ghi789',
    executedAt: '2025-11-05T14:30:00Z',
  },
  {
    id: 'pay3',
    subscriptionId: '3',
    amount: 5,
    currency: 'ADA',
    status: 'success',
    txHash: 'ghi789jkl012',
    executedAt: '2025-11-10T09:15:00Z',
  },
];

export const mockSpendingAnalytics = {
  totalMonthly: 120,
  totalYearly: 1440,
  activeSubscriptions: 8,
  byCategory: [
    { category: 'News & Content', amount: 22, count: 2 },
    { category: 'DeFi Tools', amount: 15, count: 1 },
    { category: 'DAO Membership', amount: 5, count: 1 },
    { category: 'NFT Services', amount: 25, count: 1 },
    { category: 'Wallet & Security', amount: 35, count: 3 },
  ],
  monthlyTrend: [
    { month: 'Jul', amount: 95 },
    { month: 'Aug', amount: 105 },
    { month: 'Sep', amount: 110 },
    { month: 'Oct', amount: 115 },
    { month: 'Nov', amount: 120 },
  ],
};